### PR TITLE
Feature: Add MAUI support

### PR DESCRIPTION
**Pull request by OmnipotentOwl**
**What kind of change does this PR introduce?**
Add support for Dotnet MAUI to Sextant by introducing a new library package that follows the existing prior art of the Xamarin Forms package. Updates for the CI/CD Pipeline were made using references from the main ReactiveUI pipelines.

**What is the current behavior?**
There is no support for Dotnet MAUI in Sextant nor is there a sample provided for using Sextant with Dotnet MAUI applications

**What is the new behavior?**
Ability to use Sextant for ViewModel-driven navigation with ReactiveUI in Dotnet MAUI applications.

**What might this PR break?**
The introduction of the new library package shouldn't break the existing Xamarin Forms or Avalonia packages. However, the changes to support Dotnet 6/7/8 may introduce breaking changes in packages outside the scope of this new functionality.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

- [X] Tested on Windows
- [ ] Tested on iOS
- [X] Tested on Android Simulator
- [ ] Tested on Android physical device
- [x] Tested on macOS Device

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/reactiveui/Sextant?pullRequest=691) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/Sextant?pullRequest=691) before we can accept your contribution.<br/><br/>:x: OmnipotentOwl [sign now](https://cla.dotnetfoundation.org/reactiveui/Sextant?pullRequest=691)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/Sextant?pullRequest=691) it.</sub>

**Comment by DanielCauser** [comment]
Hello, I cannot find a discussion regarding Sextant support for .net Maui. Is there any timeline for this?

**Comment by OmnipotentOwl** [comment]
> Hello, I cannot find a discussion regarding Sextant support for .net Maui. Is there any timeline for this?

Apologies for not checking this more often... This particular contribution has been something I have been working on slowly on the side and is not something I've discussed with the maintainers. I have the package in a local version for net6.0 and am looking at what it would take to move it to net8.0 hopefully without breaking some of the other libraries that are in the repo.

**Comment by OmnipotentOwl** [comment]
@glennawatson, Do you want me to go ahead and update the CI and Release workflows to match how the main ReactiveUI workflows are designed now? The current CI for Sextant still includes netcore3.1 and net5.0 and I am not sure about the current stance for support for those frameworks for this library.

**Comment by ChrisPulman** [comment]
> @glennawatson, Do you want me to go ahead and update the CI and Release workflows to match how the main ReactiveUI workflows are designed now? The current CI for Sextant still includes netcore3.1 and net5.0 and I am not sure about the current stance for support for those frameworks for this library.

Yes please, only supported framework TFM's should be used, thank you very much.

**Comment by OmnipotentOwl** [comment]
The build samples workflow should now run after doing some repair work on it in my fork and testing it over there. I also turned off the flag for the mauicheck tool in the CI after the failures it was throwing didn't seem to impact the actual usage.

**Comment by OmnipotentOwl** [comment]
It looks like the unit test phase of the build is failing because netcore3.1 is needed for testing Sextant.Plugins.Popup.Tests. Do you want me to carry this forward with these changes or take out the tests for it? The dependency looks to be on [Rg.Plugins.Popup](https://www.nuget.org/packages/Rg.Plugins.Popup#dependencies-body-tab) which only goes up to netcore3.1 for the latest package version.

**Comment by glennawatson** [comment]
Yeah feel free to remove until we find a replacement.

**Comment by ChrisPulman** [comment]
For the net8.0 target can you add `<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" />`
It's not automatically included

**Comment by ChrisPulman** [comment]
The Serialisation warnings may need to be resolved too, Binary Serialisation is depreciated, the should be a link to the instructions on how to resolve this.

**Comment by OmnipotentOwl** [comment]
> For the net8.0 target can you add `<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" />` It's not automatically included

Updated with code copied from ReactiveUI.Maui.

```csharp
<ItemGroup Condition="$(TargetFramework.StartsWith('net8'))">
  <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
  <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
</ItemGroup>
```

**Comment by ChrisPulman** [comment]
> > For the net8.0 target can you add `<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" />` It's not automatically included
> 
> Updated with code copied from ReactiveUI.Maui.
> 
> ```cs
> <ItemGroup Condition="$(TargetFramework.StartsWith('net8'))">
>   <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
>   <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
> </ItemGroup>
> ```

Perfect, this ensures the package is always the correct one 😊

**Comment by OmnipotentOwl** [comment]
> The Serialisation warnings may need to be resolved too, Binary Serialisation is depreciated, there should be a link to the instructions on how to resolve this. https://aka.ms/dotnet-warnings/SYSLIB0051

That warning is located here: 
image

Would it be appropriate to remove the protected constructor from all framework versions or is this something to just mark as obsolete and move on?

**Comment by ChrisPulman** [comment]
> > The Serialisation warnings may need to be resolved too, Binary Serialisation is depreciated, there should be a link to the instructions on how to resolve this. https://aka.ms/dotnet-warnings/SYSLIB0051
> 
> That warning is located here: image
> 
> Would it be appropriate to remove the protected constructor from all framework versions or is this something to just mark as obsolete and move on?
> 
> >  GitHub**[[Breaking change]: Legacy serialization infrastructure APIs marked obsolete · Issue #34893 · dotnet/docs](https://github.com/dotnet/docs/issues/34893)**Description Beginning with .NET 8 Preview 4, most of the legacy serialization infrastructure (the infrastructure which supports SerializableAttribute and ISerializable, along with infrastructure wh...

This is the same action I took for the other projects, so I believe it is the best option.

**Comment by ChrisPulman** [comment]
I am fairly certain that this release will be a breaking change release anyway,  so better to put people on a new course that is forward compatible.

**Comment by ChrisPulman** [comment]
The tests are failing now, but at least the main build is good. Step by step it's getting there. Thank you for your efforts

**Comment by OmnipotentOwl** [comment]
> The tests are failing now, but at least the main build is good. Step by step it's getting there. Thank you for your efforts

For the API Approved tests, what do I need to do to pass them, or because of the new frameworks they are expected to fail?

**Comment by ChrisPulman** [comment]
Could you please run the tests on your machine to get the API checks updated

**Comment by ChrisPulman** [comment]
> > The tests are failing now, but at least the main build is good. Step by step it's getting there. Thank you for your efforts
> 
> For the API Approved tests, what do I need to do to pass them, or because of the new frameworks they are expected to fail?

When you run the tests two files are created,  the verified file must match the discovered file, VS Code can be used to do the comparison

**Comment by OmnipotentOwl** [comment]
> > > The tests are failing now, but at least the main build is good. Step by step it's getting there. Thank you for your efforts
> > 
> > 
> > For the API Approved tests, what do I need to do to pass them, or because of the new frameworks they are expected to fail?
> 
> When you run the tests two files are created, the verified file must match the discovered file, VS Code can be used to do the comparison

When I run the tests locally I see the Approved files are generated as empty files but the tests still fail based on them being empty. Looking at the verified files they are also empty is this the expected output?

**Comment by OmnipotentOwl** [comment]
One other strange observation is the net8.0 target framework name isnt pulling through so the approved version is named "ApiApprovalTests.Sextant..approved.txt"

**Comment by ChrisPulman** [comment]
> One other strange observation is the net8.0 target framework name isnt pulling through so the approved version is named "ApiApprovalTests.Sextant..approved.txt"

I can take a look and fix it if required, I have had to fix it in other repositories too so not a surprise this is failing

**Comment by OmnipotentOwl** [comment]
I figured out the process for the updates to the txt files so they should be in the last commit now

**Comment by ChrisPulman** [comment]
I will try to see what is happening at some point before my flight.

**Comment by ChrisPulman** [comment]
if you can pull across the changes I made in #725 then this should fix the API issues, and mostly update the packages in the solution. I can't commit to your fork so I did this to try and help.

**Comment by OmnipotentOwl** [comment]
> if you can pull across the changes I made in #725 then this should fix the API issues, and mostly update the packages in the solution. I can't commit to your fork so I did this to try and help.

Thank you for that help, I cherry-picked your commit from that PR over to this one so we should be able to run the tests again.

**Comment by OmnipotentOwl** [comment]
Ok, now I think that's everything fixed for build and samples... Tests worked and passed and with the samples updated, we should be good. I do still want to run a manual test on my end for macos to make sure that works properly if I can get my build host working properly for that.

**Comment by ChrisPulman** [comment]
I will be going to the airport in about 5 hours, then I will be offline for about 14 hours. Glenn may be able to assist you with pushing the build runs, but I am not sure of his movements.

**Comment by OmnipotentOwl** [comment]
> I will be going to the airport in about 5 hours, then I will be offline for about 14 hours. Glenn may be able to assist you with pushing the build runs, but I am not sure of his movements.

Thank you both for your support in this effort. I am hopeful that there will be no more issues with the samples and that we can wrap this up soon. I tested the code on MacOS and it ran fine without any issues that I could visibly see with the sample app.

**Review by ChrisPulman — APPROVED** [review]

**Comment by OmnipotentOwl** [comment]
Are there any more criteria you would like to see added before merging these changes? If no do you want me to merge the changes or is there a preview build you all would put out with this to field test it any further?

**Pull request merged**
